// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source interface.go -destination=mock_interface.go -package=task
//

// Package task is a generated GoMock package.
package user

import (
	models "awesomeProject/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockUserStore) AddUser(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockUserStoreMockRecorder) AddUser(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockUserStore)(nil).AddUser), name)
}

// CheckIfRowsExists mocks base method.
func (m *MockUserStore) CheckIfRowsExists() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfRowsExists")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckIfRowsExists indicates an expected call of CheckIfRowsExists.
func (mr *MockUserStoreMockRecorder) CheckIfRowsExists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfRowsExists", reflect.TypeOf((*MockUserStore)(nil).CheckIfRowsExists))
}

// CheckUserID mocks base method.
func (m *MockUserStore) CheckUserID(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserID", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckUserID indicates an expected call of CheckUserID.
func (mr *MockUserStoreMockRecorder) CheckUserID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserID", reflect.TypeOf((*MockUserStore)(nil).CheckUserID), id)
}

// GetUserByID mocks base method.
func (m *MockUserStore) GetUserByID(id int) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserStoreMockRecorder) GetUserByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserStore)(nil).GetUserByID), id)
}

// ViewUser mocks base method.
func (m *MockUserStore) ViewUser() ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewUser")
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewUser indicates an expected call of ViewUser.
func (mr *MockUserStoreMockRecorder) ViewUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewUser", reflect.TypeOf((*MockUserStore)(nil).ViewUser))
}
